server:
  port: 9010

spring:
  application:
    name: cloud-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#
eureka:
  client:
    # 表示是否将自己注册进 EurekaServer
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10002/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

# 设置 feign 客户端超时时间 （feign 默认支持 ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间上限
  ReadTimeout: 5000
  # 建立连接后从服务器读取可用资源所用时间上限
  ConnectTimeout: 5000

logging:
  level:
    net.yisasin.springcloud.feign.*: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.yisasin.springcloud.entity